const API_KEY = process.env.API_KEY;
import Head from "next/head";
import react, { useState } from "react";
import Image from "next/image";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Result from "../components/Result";

export default function Home({ results }) {
  let arr = new Array();
  arr.push(results);
  console.log(arr);
  // if (typeof window !== "undefined") {
  //   // Perform localStorage action
  //   localStorage.setItem("data", JSON.stringify(arr));
  // }

  console.log(results);
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* Nav */}
      {/* Content/result */}
      <Result results={results} />
      {/* Footer */}
      <Footer />
    </div>
  );
}

export async function getServerSideProps(context) {

  const query = context.query.dish || "dosa"
console.log(query,"thie s query");
  const options = {
    method: "GET",
    headers: {
      "X-RapidAPI-Host": "recipesapi2.p.rapidapi.com",
      "X-RapidAPI-Key": API_KEY,
    },
  };
  // let request = "";

  const request = await fetch(
    `https://recipesapi2.p.rapidapi.com/recipes/${query}`,
    options
  )
    .then((response) => response.json())

    .catch((err) => console.error(err));
  console.log(request.data);
  return {
    props: {
      results: request.data || null,
    },
  };
}
